PermanentOrg/permanent-ios

Permanent.xcodeproj/project.pbxproj, Permanent/Constants/Constants.swift, Permanent/Models/Data/AccountUpdateVO.swift, Permanent/Models/Payloads.swift, Permanent/Network/AccountEndpoint.swift, Permanent/Network/AuthenticationEndpoint.swift, Permanent/Security/LocalAuthentication/PermanentLocalAuthentication.swift, Permanent/Storyboards/Authentication.storyboard, Permanent/ViewControllers/Authentication/BiometricsViewController.swift, Permanent/ViewControllers/Authentication/CodeVerificationController.swift, Permanent/ViewControllers/Authentication/LoginViewController.swift, Permanent/ViewControllers/Authentication/SignUpViewController.swift, Permanent/ViewControllers/Authentication/TwoStepVerificationViewController.swift, Permanent/ViewModels/AccountViewModel.swift, Permanent/ViewModels/AuthViewModel.swift, Permanent/ViewModels/VerificationCodeViewModel.swift
- Make API call to send SMS after updating the phone number
=> Implement flow to validate the phone number

Permanent.xcodeproj/project.pbxproj, Permanent/Assets/Localization/en.lproj/Localizable.strings, Permanent/Constants/Translations.swift, Permanent/Extensions/ArrayExtension.swift, Permanent/Helpers/DateUtils.swift, Permanent/Models/Data/Folder/ChildItemVO.swift, Permanent/Models/Data/Folder/FolderVO.swift, Permanent/Models/Data/Folder/MinFolderVO.swift, Permanent/Models/Data/RecordVO.swift, Permanent/Storyboards/Main.storyboard, Permanent/ViewControllers/MainViewController.swift, Permanent/ViewModels/FilesViewModel.swift, Permanent/ViewModels/UI/FileListType.swift, Permanent/ViewModels/UI/FileStatus.swift, Permanent/ViewModels/UI/FileViewModel.swift, Permanent/Views/Cells/FileTableViewCell.swift, Permanent/Views/Cells/FileTableViewCell.xib
=> File sync (work in progress)

Permanent/Assets/Assets.xcassets/cloud.imageset/Contents.json, Permanent/Assets/Assets.xcassets/cloud.imageset/cloud.pdf, Permanent/Assets/Localization/en.lproj/Localizable.strings, Permanent/Constants/Constants.swift, Permanent/Constants/Translations.swift, Permanent/Models/FileInfo.swift, Permanent/Services/PreferencesManager.swift, Permanent/ViewControllers/MainViewController.swift, Permanent/ViewModels/FilesViewModel.swift, Permanent/ViewModels/UI/FileViewModel.swift, Permanent/Views/Cells/FileTableViewCell.swift, Permanent/Views/Cells/FileTableViewCell.xib
=> Further implementation of file sync functionality

Permanent.xcodeproj/project.pbxproj, Permanent/Constants/Constants.swift, Permanent/Helpers/UploadManager.swift, Permanent/Models/FileInfo.swift, Permanent/Models/FolderInfo.swift, Permanent/Network/FilesEndpoint.swift, Permanent/Network/Layer/APINetworkSession.swift, Permanent/Services/PreferencesManager.swift, Permanent/ViewControllers/Authentication/BiometricsViewController.swift, Permanent/ViewControllers/Authentication/LoginViewController.swift, Permanent/ViewControllers/MainViewController.swift, Permanent/ViewModels/FilesViewModel.swift, Permanent/ViewModels/UI/FileViewModel.swift, Permanent/Views/Cells/FileTableViewCell.swift
1. Logic to upload from multiple folders and modify UI accordingly. 
2. Resume upload process at app start if killed by OS or user.
3. Display real progress when uploading file. 
4. Perform biometrics auth automatically. 
5. Perform login API call when dismissing the keyboard.
=> Uploads resume logic

Permanent/Network/FilesEndpoint.swift, Permanent/Network/Layer/APINetworkSession.swift, Permanent/Network/Layer/APIRequestDispatcher.swift, Permanent/Network/Layer/NetworkSessionProtocol.swift, Permanent/ViewControllers/MainViewController.swift, Permanent/ViewModels/FilesViewModel.swift, Permanent/Views/Cells/FileTableViewCell.swift
- Add real progress when downloading
- Replace dataTask with downloadTask implementation
Left to do: 
- cancel ongoing download
- resume downloads
=> Fix download issue (work in progress)

Permanent/Extensions/StringExtension.swift, Permanent/Views/Cells/FileTableViewCell.xib, Permanent/Views/Share Link/InputSettingsView.swift
=> Minor UI bugfixes

Permanent/Extensions/URLExtension.swift, Permanent/Models/Payloads.swift, Permanent/Views/Cells/FileTableViewCell.swift, Podfile
=> Add SDWebImage library

Permanent.xcodeproj/project.pbxproj, Permanent/Network/Layer/APINetworkSession.swift, Permanent/Network/SharedURLSession.swift
=> - Re use session for data tasks

Permanent.xcodeproj/project.pbxproj, Permanent/Models/Payloads/AccountVOPayload.swift, Permanent/Models/Payloads/ArchiveSharePayload.swift, Permanent/Network/MembersEndpoint.swift, Permanent/ViewControllers/MembersViewController.swift, Permanent/ViewModels/MembersViewModel.swift
=> Make API call to add new member to archive

Permanent.xcodeproj/project.pbxproj, Permanent/Storyboards/Main.storyboard, Permanent/ViewControllers/FilePreviewViewController.swift, Permanent/ViewControllers/ImagePreviewViewController.swift, Permanent/ViewModels/FilePreviewViewModel.swift
- created ViewController for previewing images
=> VSP-231 [iOS] Some videos or images are misaligned in File Preview screen

Permanent/Assets/Info.plist, Permanent/ViewControllers/FileDetailsViewController.swift, Permanent/ViewControllers/FilePreviewNavigationController.swift, Permanent/ViewControllers/FilePreviewViewController.swift, Permanent/ViewControllers/RootViewController.swift
- added support for landscape mode in the file preview screen
=> VSP-233 [iOS] Enable landscape mode for file preview

Permanent.xcodeproj/project.pbxproj, Permanent/Models/Data/LocnVO.swift, Permanent/ViewControllers/FileDetailsViewController.swift, Permanent/Views/Cells/FileDetailsCollectionViewCells/FileDetailsMapViewCellCollectionViewCell.swift, Permanent/Views/Cells/FileDetailsCollectionViewCells/FileDetailsMapViewCellCollectionViewCell.xib
Added map view in file metadata
=> VSP-194 [iOS] Ability to show map location from file metadata

.gitmodules, Permanent.xcodeproj/project.pbxproj, Permanent/Constants/Constants.swift, Permanent/Constants/StoryboardName.swift, Permanent/Extensions/UIViewExtension.swift, Permanent/Models/Data/LocnVO.swift, Permanent/Models/Payloads.swift, Permanent/Network/LocationEndpoint.swift, Permanent/Storyboards/Main.storyboard, Permanent/ViewControllers/FileDetailsViewController.swift, Permanent/ViewControllers/LocationSetViewController.swift, Permanent/ViewControllers/NavigationController.swift, Permanent/ViewModels/FilePreviewViewModel.swift, Permanent/Views/Cells/FileDetailsCollectionViewCells/FileDetailsBottomCollectionViewCell.swift, Permanent/Views/Cells/FileDetailsCollectionViewCells/FileDetailsMapViewCellCollectionViewCell.swift, Permanent/Views/Cells/FileDetailsCollectionViewCells/FileDetailsMapViewCellCollectionViewCell.xib, Podfile, Podfile.lock
New screen was added for editing file location metadate.
=> VSP-237 [iOS] Ability to edit location meta data

Permanent/Extensions/PHAssetExtension.swift, Permanent/Models/FileInfo.swift, Permanent/ViewControllers/MainViewController.swift, Permanent/ViewModels/FilesViewModel.swift
- fixed a crash which happened when trying to upload files that are stored on iCloud, not on the local device storage
- fixed multiple upload issue by adding a check for duplicates in the upload queue
=> VSP-258 [iOS] Uploading issue

Permanent.xcodeproj/project.pbxproj, Permanent/Models/Data/TagLinkVO.swift, Permanent/Models/Data/TagVO.swift, Permanent/Models/Payloads.swift, Permanent/Network/TagEndpoint.swift, Permanent/ViewControllers/FileDetailsViewController.swift, Permanent/ViewModels/FilePreviewViewModel.swift
Added API request implementations for the following endpoints:
/tag/post
/tag/delete
/tag/getTagsByArchive
=> VSP-264 [iOS] Tags api implementation

Permanent.xcodeproj/project.pbxproj
=> - remove automatic signing for DEV-Release

Permanent.xcodeproj/project.pbxproj, Permanent/AppDelegate.swift, Permanent/Models/Data/FileType.swift, Permanent/ViewControllers/FilePreviewViewController.swift, Permanent/ViewModels/FilePreviewViewModel.swift, Podfile.lock, PushExtension/NotificationService.swift
Added notifications for shared file.
=> VSP-271 [iOS] Push notification - Shared file

Permanent/Extensions/UIViewExtension.swift, Permanent/Storyboards/Settings.storyboard, Permanent/ViewControllers/AccountDeleteViewController.swift, Permanent/ViewControllers/AccountInfoViewController.swift, Permanent/ViewControllers/Authentication/SignUpViewController.swift, Permanent/ViewModels/AccountDeleteViewModel.swift, Permanent/ViewModels/AuthViewModel.swift, PushExtension/NotificationService.swift
- Added a notification for user that account was deleted 
- Added spinner when deleting account
- Updated text for delete account (provided by Robert) 
- Updated Notifications text from google sheet document provided by Permanent team
- Updated Delete account button to read “Delete Account“
- Removed push token when deleting the account
=> VSP-354 [iOS] Final UI improvements

Permanent/ViewControllers/MainViewController.swift
Fixed open Photos library on first application launch.
=> VSP-360 [iOS] Initial opening of photo library for upload is empty

Permanent/ViewControllers/AccountInfoViewController.swift, Permanent/ViewControllers/Authentication/CodeVerificationController.swift, Permanent/Views/AccountInfo/InputTextWithLabelElementViewViewController.swift
- Added Done button to numpad keyboard for Code Verification after SigIn step.
- Changed to numbersAndPunctuation keyboard in Account Info screen when you are entering your phone number(note: only digits can be added)
=> VSP-319 [iOS] Verification code screen - numeric keyboard

Permanent/Storyboards/Authentication.storyboard, Permanent/Storyboards/Onboarding.storyboard, Permanent/ViewControllers/Onboarding/OnboardingPageThree.swift
Changed onboarding screens constrains for small screen devices.
=> VSP-318 [iOS] First time user flow - screens

Permanent/Storyboards/Share.storyboard, Permanent/ViewControllers/ShareViewController.swift, Permanent/Views/Cells/ArchiveTableViewCell/ArchiveTableViewCell.swift, Permanent/Views/Cells/ArchiveTableViewCell/ArchiveTableViewCell.xib
Removed white space when request was approved or denied.
=> VSP-346 [iOS] UI issue when in Shared Link Screen.

Permanent/Views/Cells/ArchiveTableViewCell/ArchiveTableViewCell.swift, Permanent/Views/Cells/ArchiveTableViewCell/ArchiveTableViewCell.xib
Added new view to include bottom buttons, fixed the issue when a part of buttons appeared randomly.
=> VSP-346-2 [iOS] UI issue when in Shared Link Screen

Permanent/ViewControllers/FilePreviewListViewController.swift, Permanent/ViewControllers/FilePreviewViewController.swift
- preload two items left and right
=> VSP-347 [iOS] Preload slideshow previous and next item for faster switching

Permanent/Models/Payloads.swift
- removed created DT hardcoding
=> VSP-387 [iOS] Uploading a photo from device's camera displays wrong timestamp after processing

Permanent.xcodeproj/project.pbxproj, Permanent/Constants/Constants.swift, Permanent/Constants/StoryboardName.swift, Permanent/Storyboards/Onboarding.storyboard, Permanent/ViewControllers/Authentication/SignUpViewController.swift, Permanent/ViewControllers/MainViewController.swift, Permanent/ViewControllers/WelcomePageViewController.swift
Added welcome screen pop-up
Added close button (X icon)
This pop-up should only appear after the account is created
=> VSP-391 [iOS] Implement Welcome pop-up

Permanent.xcodeproj/project.pbxproj, Permanent/Assets/Localization/en.lproj/Localizable.strings, Permanent/Constants/Constants.swift, Permanent/Constants/Strings.swift, Permanent/ViewControllers/AccountInfoViewController.swift, Permanent/ViewModels/InfoViewModel.swift, PermanentTests/AccountInfoTests.swift, PermanentTests/LoginTests.swift, PermanentTests/SignUpTests.swift, PermanentTests/VerificationCodeTests.swift
- Added unit tests.
- Changed link to termsConditionsURL at signUp screen.
=> Added unit tests for InfoViewModel.swift methods.

Permanent.xcodeproj/project.pbxproj, Permanent/AppDelegate.swift, Permanent/Assets/Localization/en.lproj/Localizable.strings, Permanent/Constants/StoryboardName.swift, Permanent/Constants/TableViewData.swift, Permanent/Extensions/UIViewExtension.swift, Permanent/Models/DrawerOption.swift, Permanent/Storyboards/Main.storyboard, Permanent/ViewControllers/DrawerViewController.swift, Permanent/ViewControllers/RightSideMenuViewController.swift, Permanent/ViewControllers/RootNavigationController.swift, Permanent/ViewControllers/RootViewController.swift, Permanent/ViewControllers/SideMenuViewController.swift, Permanent/ViewModels/AuthViewModel.swift, Permanent/Views/Cells/DrawerTableViewCell/DrawerTableViewCell.swift, Permanent/Views/Cells/DrawerTableViewCell/RightSideDrawerTableViewCell.swift, Permanent/Views/Cells/DrawerTableViewCell/RightSideDrawerTableViewCell.xib
Added right side menu functionality.
=> VSP-171 Right Side Menu

Permanent/Constants/Strings.swift, Permanent/Scenes/ViewController.swift, Permanent/Storyboards/Main.storyboard, Permanent/ViewControllers/BaseViewController.swift, Permanent/ViewControllers/MainViewController.swift, Permanent/ViewControllers/RightSideMenuViewController.swift, Permanent/Views/ActionDialogView/ActionDialogView.swift, Permanent/Views/ActionDialogView/ActionDialogView.xib
Added confirmation pop-up for cancel all uploads functionality.
Added remaining storage space in right drawer.
=> VSP-459,VSP-461 [iOS] Confirm Alert for cancel all

Permanent/ViewControllers/RightSideMenuViewController.swift, Permanent/ViewModels/AuthViewModel.swift
Changed space left and total space available display mode in right side menu.
=> VSP-461 [iOS] Show remaining space as well in right drawer

Permanent/Constants/Strings.swift, Permanent/Network/APIErrors.swift, Permanent/ViewControllers/Authentication/LoginViewController.swift, Permanent/ViewModels/AuthViewModel.swift, Permanent/ViewModels/InfoViewModel.swift
- Fixed forgot password issue, where there was no validation of email inserted by the user.
- The same issue was fixed in Account details screen.
=> VSP-479 [iOS] Forgot password is not verifying if it is an email.

Permanent/ViewControllers/MainViewController.swift
Interchanged "Cancel", "Delete" buttons color in delete file alert.
=> VSP-473 [iOS] Delete confirmation button is blue, cancel is red

Permanent/Storyboards/Main.storyboard, Permanent/ViewControllers/FilePreviewViewController.swift
=> VSP-426 [iOS] Shared with me: files should load in file view.

Permanent/ViewControllers/ArchivesViewController.swift
- disabled buttons while the request is in progress
=> VSP-579 iOS: Tried to create an archive, may have accidentially clicked twice and it created two separate archives

Permanent/ViewModels/VerificationCodeViewModel.swift
- added logic to grab the current archive after the verification code is validated by the server
At first login, the list of archive that the user has access to is not retrieved during the authentication call. However after the verification code is sent and approved by the server, we can do another call to grab the list of available archives and figure out what the default archive is.
=> VSP-602 [iOS] Archive Permissions are wrong after fresh install

Permanent.xcodeproj/project.pbxproj, Permanent/Constants/ProfilePageData.swift, Permanent/Models/Data/PublicProfile/EstablishedInfoProfileItem.swift, Permanent/Models/Data/PublicProfile/ProfileItemVO.swift, Permanent/Models/Enums/FieldNameUI.swift, Permanent/Storyboards/Profile.storyboard, Permanent/ViewControllers/Profile/PublicProfilePageViewController.swift, Permanent/ViewControllers/Profile/PublicProfilePersonalInfoViewController.swift, Permanent/ViewModels/PublicProfilePageViewModel.swift, Permanent/Views/Cells/ProfilePageCollectionViewCells/ProfilePageFooterCollectionViewCell.swift, Permanent/Views/Cells/ProfilePageCollectionViewCells/ProfilePageInformationCollectionViewCell.swift, Permanent/Views/Cells/ProfilePageCollectionViewCells/ProfilePageInformationCollectionViewCell.xib, Permanent/Views/Cells/ProfilePageCollectionViewCells/ProfilePagePersonInfoCollectionViewCell.swift
- Added Family and Organization Information API/Mapping
- Public Archive - Family/Group Information
- Public Archive - Organization Information
- Ui adjustments (read more -> show more, spacing)
- Refactor Profile Page
=> VSP-623 [iOS] Public Archive - Family/Organization Information

Permanent/Storyboards/Profile.storyboard, Permanent/ViewControllers/AccountDeleteViewController.swift, Permanent/ViewControllers/Profile/PublicProfileAddMilestonesViewController.swift, Permanent/ViewControllers/Profile/PublicProfileMilestonesViewController.swift, Permanent/Views/Cells/MilestonesTableCells/MilestonesTableViewCell.swift
1. In Edit Milestones Screen:
- Added Milestone title, location, start data and end date for every item
2. In Edit Milestone/Add Milestone Screens:
- Changed Description textField to textView( for being able to add new lines )
- Changed Places of Description with Location
3. Fixed an issue in Edit Milestone Screen, where description field couldn't be edited when keyboard was shown.
=> VSP-667[iOS] Improve Milestone screen after demo suggestions

Permanent/Constants/Strings.swift, Permanent/Models/DrawerOption.swift, Permanent/ViewControllers/RightSideMenuViewController.swift
- Added Contact Support menu button to right side menu.
- Resolved SwiftLint warnings for modified files.
=> VSP-423[iOS] Contact Support

Permanent/Constants/Strings.swift, Permanent/Models/Payloads/RecordVOPayload.swift, Permanent/Models/Payloads/RelocateRecordPayload.swift, Permanent/Network/FilesEndpoint.swift, Permanent/ViewControllers/MainViewController.swift, Permanent/ViewModels/FilesViewModel.swift, Permanent/ViewModels/UI/FileViewModel.swift
- Added Publish option for files/folders in Private Files/Folders screen
- Added backend functionality for being able to publish files/folders
- Resolved SwiftLint warnings for modified files.
=> VSP-211 [iOS] Publish File/Folder Screen

Permanent.xcodeproj/project.pbxproj, Permanent/Models/Payloads.swift, Permanent/Network/PublicProfilePageEndpoint.swift, Permanent/Storyboards/Profile.storyboard, Permanent/ViewControllers/Profile/PublicProfilePageViewController.swift, Permanent/ViewModels/PublicProfilePageViewModel.swift, Permanent/Views/Cells/ProfilePageCollectionViewCells/ProfilePageHeaderCollectionViewCell.xib, Permanent/Views/Cells/ProfilePageCollectionViewCells/ProfilePageVisibilityCollectionViewCell.swift, Permanent/Views/Cells/ProfilePageCollectionViewCells/ProfilePageVisibilityCollectionViewCell.xib
- created public visibility cell
- implemented public visibility section in the public profile page
- added api implementation for updating visibility
=> VSP-687 iOS: Implement Profile Visibility toggle in the Public Profile

Permanent/AppDelegate.swift, Permanent/Assets/Localization/en.lproj/Localizable.strings, Permanent/Models/Data/AttachmentRecordVO.swift, Permanent/Network/ArchivesEndpoint.swift, Permanent/Network/AuthenticationEndpoint.swift, Permanent/ViewControllers/BasePageViewController.swift, Permanent/ViewControllers/ShareViewController.swift, Permanent/ViewModels/ArchivesViewModel.swift, Permanent/Views/Cells/ArchiveTableViewCell/ArchiveScreenChooseArchiveDetailsTableViewCell.swift, Permanent/Views/Cells/ArchiveTableViewCell/ArchiveScreenPendingArchiveDetailsTableViewCell.swift, Permanent/Views/Cells/ArchiveTableViewCell/ArchiveScreenSectionTitleTableViewCell.swift, Permanent/Views/Cells/ArchiveTableViewCell/ArchiveTableViewCell.swift, Permanent/Views/Cells/ArchiveTableViewCell/ArchiveTableViewCell.xib
- Changed "My files" text
- Updated Approve/Deny button actions for "Share in Permanent" screen
- Resolved some SwiftLint warnings
=> VSP-690 [iOS]: All the headings still say "My Files"

Permanent/Managers/Upload/UploadManager.swift, Permanent/Views/Cells/FileCollectionViewCell.swift
Modified upload method for being able to upload multiple files.
=> VSP-431 [iOS] As a user I would like to be able to have multiple uploads at the same time

Permanent/ViewControllers/MainViewController.swift, Permanent/ViewModels/FilesViewModel.swift
Added automatic refresh method after upload of files was completed.
=> VSP-471 [iOS] Files which have finished processing are stuck with a spinner until manual refresh

Permanent/Models/Data/FileType.swift, Permanent/ViewControllers/FilePreviewViewController.swift, Permanent/Views/Cells/FileDetailsCollectionViewCells/FileDetailsTopCollectionViewCell.swift, Podfile, Podfile.lock
- added pdf file type
- added caching to the details photo
- implemented PDFView for viewing pdfs
=> VSP-712 [iOS] PDF Native viewer

Permanent/Storyboards/Main.storyboard, Permanent/ViewControllers/PublicGalleryViewController.swift, Permanent/Views/Cells/ArchiveTableViewCell/ArchiveTableViewCell.swift, Permanent/Views/Cells/ArchiveTableViewCell/ArchiveTableViewCell.xib, Permanent/Views/Cells/PublicGalleryCollectionViewCells/PublicGalleryCellCollectionViewCell.swift
Added navigation to Profile Page screen when profile thumbnail is tapped in Public Gallery screen
=> VSP-764 [iOS] Navigate to profile page when profile image is tapped in Public Gallery screen

Permanent/ViewModels/PublicProfilePageViewModel.swift
Changed archive change permission to Owner and Manager roles.
=> VSP-766 [iOS] Public Profile Permissions update

Permanent.xcodeproj/project.pbxproj, Permanent/Constants/Constants.swift, Permanent/Constants/StoryboardName.swift, Permanent/Extensions/UITapGestureRecognizerExtension.swift, Permanent/Storyboards/AccountOnboarding.storyboard, Permanent/Storyboards/Onboarding.storyboard, Permanent/ViewControllers/AccountOnboarding/AccountOnboardingPageOneWithPendingArchives.swift, Permanent/ViewControllers/AccountOnboarding/AccountOnboardingPageTwoWithPendingArchives.swift, Permanent/ViewControllers/AccountOnboarding/AccountOnboardingViewController.swift, Permanent/ViewControllers/Authentication/BiometricsViewController.swift, Permanent/ViewControllers/Authentication/SignUpViewController.swift, Permanent/ViewControllers/MainViewController.swift, Permanent/ViewControllers/WelcomePageViewController.swift, Permanent/ViewModels/AccountOnboardingViewModel.swift, Permanent/ViewModels/AuthViewModel.swift, Permanent/Views/Cells/AccountOnboarding/AccountOnboardingAcceptArchiveTableViewCell.swift, Permanent/Views/Cells/AccountOnboarding/AccountOnboardingAcceptArchiveTableViewCell.xib, Permanent/Views/Cells/AccountOnboarding/AccountOnboardingHeaderTableViewCell.swift, Permanent/Views/Cells/AccountOnboarding/AccountOnboardingHeaderTableViewCell.xib, Permanent/Views/Cells/AccountOnboarding/AccountOnboardingMakeDefaultArchiveTableViewCell.swift, Permanent/Views/Cells/AccountOnboarding/AccountOnboardingMakeDefaultArchiveTableViewCell.xib, Permanent/Views/Cells/ArchiveTableViewCell/ArchiveScreenChooseArchiveDetailsTableViewCell.xib
- Added Pending archives screen for Account Onboarding functionality
- Set position for Accept button in pending archives screen to the right of the cell
- Change to open pending archives screen only when the account have pending archives
- Added functionality to accept button on pending archives screen
- Added "Confirmation: Invitation Accepted" screen which will be displayed after all pending archives were accepted by the user.
- Updated onboarding navigation
- Implemented onboarding welcome messages
- Minor UI fixes
=> VSP-700 [iOS] Pending Archive Invitations Screen

Permanent.xcodeproj/project.pbxproj, Permanent/ViewControllers/PublicGalleryViewController.swift, Permanent/ViewModels/PublicGalleryViewModel.swift, Permanent/Views/Cells/PublicGalleryCollectionViewCells/PublicGalleryNoArchiveCellCollectionViewCell.swift, Permanent/Views/Cells/PublicGalleryCollectionViewCells/PublicGalleryNoArchiveCellCollectionViewCell.xib
Added help cell for empty Personal Public Gallery
=> VSP-778 [iOS] Placeholder for no public archives with link to how to

Permanent.xcodeproj/project.pbxproj, Permanent/Extensions/AVCaptureDeviceExtension.swift, Permanent/Helpers/MediaRecorder.swift
Added alert for permission to access camera when the user whats to add a photo from the camera.
=> VSP-464 [iOS] Camera view shown despite denying permission to access camera

Permanent/AppDelegate.swift, Permanent/Models/Data/ShareNotificationPayload.swift, Permanent/ViewControllers/FilePreviewViewController.swift, Permanent/ViewControllers/SharesViewController.swift, Permanent/ViewModels/FilePreviewViewModel.swift, Permanent/ViewModels/UI/FileViewModel.swift, Permanent/Views/Cells/FileDetailsCollectionViewCells/FileDetailsTopCollectionViewCell.swift
Resolved the following issues :
- Open fullscreen image after tapping a shared notification
- Setting current permissions for shared file
=> VSP-796 [iOS] Image preview after tapping a share link notification doesn't work

Permanent/ViewControllers/MainViewController.swift, Permanent/ViewControllers/RightSideMenuViewController.swift
- Added Contact Support section on right side menu
- Fixed navigation when running out of storage(from web link to in app Add Storage screen)
=> VSP-798 [iOS] Add help/support links

Permanent/Scenes/PhotoPicker/AssetGridViewController.swift, Podfile.lock
Added iOS Photos app navigation style to Photo Library picker screen
=> VSP-803 [iOS] Gallery photo viewer vertical order change to match with iOS photos app

Permanent/Managers/Upload/UploadManager.swift, Permanent/ViewControllers/MainViewController.swift, Permanent/ViewModels/FilesViewModel.swift
- added a "Preparing files" UI
- copied iCloud files locally while the "preparing" UI is on screen
=> VSP-842 [iOS] iCloud files fail to upload sometimes

Permanent.xcodeproj/project.pbxproj, Permanent.xcodeproj/project.pbxproj.rej, Permanent/Models/Payloads.swift, Permanent/Network/FilesEndpoint.swift, Permanent/Storyboards/Archives.storyboard, Permanent/Storyboards/Share.storyboard, Permanent/ViewControllers/SharesViewController.swift, Permanent/ViewModels/SharedFilesViewModel.swift, Permanent/Views/Cells/FileCollectionViewCell.swift, Podfile.lock, Podfile.lock.rej, Podfile.rej, ShareExtension/ShareExtensionDEV-Release.entitlements, fastlane/Appfile, fastlane/Fastfile, fastlane/README.md
The following tasks were also implemented:
- Fixed issues for shared files menu [VSP-894]
- Add ability to unshare a file from an archive [VSP-409]
=> VSP-838 [iOS] Ability to move a file/folder from a share folder

Permanent/ViewControllers/SharesViewController.swift, Permanent/Views/ActionDialogView/ActionDialogView.xib, Permanent/Views/RoundedButton.swift
Changed action dialog text for back navigation in shared files screen
=> VSP-900 [iOS] Update navigate back alert text when there's a file selected

Permanent/ViewControllers/ArchivesViewController.swift, Permanent/ViewControllers/PRMNTActionSheetViewController.swift, Permanent/ViewControllers/Profile/PublicArchiveFileViewController.swift, Permanent/ViewControllers/Profile/PublicProfileMilestonesViewController.swift, Permanent/ViewControllers/Profile/PublicProfileOnlinePresenceViewController.swift, Permanent/ViewControllers/ShareViewController.swift
=> VSP-908 [iOS] Make menu header blue

Permanent.xcodeproj/project.pbxproj, Permanent/Constants/Colors.swift, Permanent/Models/Data/TagVO.swift, Permanent/Models/Payloads.swift, Permanent/Models/Repositories/Datasources/Local/TagsLocalDataSource.swift, Permanent/Models/Repositories/Datasources/Remote/TagsRemoteDataSourceInterface.swift, Permanent/Models/Repositories/TagsRepository.swift, Permanent/Network/TagEndpoint.swift, Permanent/ViewControllers/TagDetailsViewController.swift, Permanent/ViewModels/FilePreviewViewModel.swift, Permanent/ViewModels/ManageTagsViewModel.swift, Permanent/ViewModels/SearchFilesViewModel.swift
Implemented delete tags, and repaired un-assign tags method.
=> VSP-881 [iOS] Manage Tags - delete tag(s)

Permanent/Models/Data/FileType.swift, Permanent/ViewControllers/ShareViewController.swift, Permanent/ViewControllers/SharesViewController.swift, Permanent/Views/ActionDialogView/ActionDialogView.xib, Permanent/Views/Cells/ArchiveTableViewCell/ArchiveTableViewCell.swift
VSP-963 [iOS] Add Owner as an option in the Share Management screen
VSP-983 [iOS] Update move navigation alert text from Shares workspace
=> VSP-963 [iOS] Implement feedback from demo #2

Permanent/ViewControllers/ShareManagementViewController.swift, Permanent/Views/Cells/ShareManagementCollectionViewCells/ShareManagementLinkAndShowSettingsCollectionViewCell.swift, Permanent/Views/Cells/ShareManagementCollectionViewCells/ShareManagementSeparatorFooterCollectionViewCell.xib, Permanent/Views/Cells/ShareManagementCollectionViewCells/ShareMangementAdditionalOptionCollectionViewCell.swift, Permanent/Views/Cells/ShareManagementCollectionViewCells/ShareMangementAdditionalOptionCollectionViewCell.xib
- Added revoke link and share link in the lower section of Share management screen.
- Resolved minor bugs for share link button and link display format
=> VSP-1025[iOS]Add buttons for different share link actions

Permanent/ViewControllers/TagDetailsViewController.swift, Permanent/ViewControllers/TagManagementViewController.swift, Permanent/ViewModels/ManageTagsViewModel.swift, Permanent/Views/Cells/ArchiveSettings/ArchiveSettingsTagsHeaderCollectionView.swift
Implemented search bar functionality, and change "Name" to the number of tasks found.
=> VSP-884 [iOS] Manage Tags - search tag name

Permanent.xcodeproj/project.pbxproj, Permanent/Constants/Constants.swift, Permanent/Constants/StoryboardName.swift, Permanent/Models/Repositories/Datasources/Local/TagsLocalDataSource.swift, Permanent/Models/Repositories/Datasources/Remote/TagsRemoteDataSourceInterface.swift, Permanent/Models/Repositories/TagsRepository.swift, Permanent/Storyboards/ArchiveSettings.storyboard, Permanent/Storyboards/Share.storyboard, Permanent/ViewControllers/TagManagementViewController.swift, Permanent/ViewModels/ManageTagsViewModel.swift, Permanent/Views/FABTagsManagementActionSheet.swift
Added "Add Tag" feature to Tags Management
=> VSP-880[iOS] Manage Tags - add new tag

Permanent/Network/FilesEndpoint.swift, Permanent/ViewControllers/MainViewController.swift, Permanent/ViewControllers/SharesViewController.swift, Permanent/Views/Cells/FileCollectionViewCell.swift
Added move multiple files functionality.
=> VSP-925[iOS]Move multiple files

Permanent/Network/FilesEndpoint.swift, Permanent/ViewControllers/MainViewController.swift, Permanent/ViewControllers/SharesViewController.swift, Permanent/ViewModels/FilesViewModel.swift
Added delete multiple files to the Private Files, Shared Files, and Public Files screens.
=> Added multiple files delete functionality to the Private Files screen.

Permanent/ViewControllers/MainViewController.swift, Permanent/ViewControllers/SharesViewController.swift, Podfile.lock
- Add an alert when you copy files in the public files, like the upload file alert.
- Add copy option for the shared files folder.
- Fix a bug where if you copy files in the same folder you get an alert that denies this.
=> VSP-1105 [iOS] Demo Feedback

Permanent/Storyboards/LegacyPlanning.storyboard, Permanent/ViewControllers/LegacyPlanning/ViewController/TrustedStewardViewController.swift
Refactor Info text from UILabel to UITextField
- Replaced the existing UILabel with a UITextField to enable user input
- Implemented dynamic sizing for the UITextField to display text according to design requirements
=> VSP-1143 [iOS] Message for the steward should be editable

Permanent/Models/Data/ArchiveVO.swift, Permanent/Models/DrawerOption.swift, Permanent/ViewControllers/ArchivesViewController.swift, Permanent/ViewControllers/LegacyPlanning/ViewController/LegacyPlanningLoadingViewController.swift, Permanent/ViewControllers/LegacyPlanning/ViewController/LegacyPlanningStewardViewController.swift, Permanent/ViewControllers/LegacyPlanning/ViewController/TrustedStewardViewController.swift, Permanent/ViewControllers/LegacyPlanning/ViewModels/LegacyPlanningViewModel.swift, Permanent/ViewControllers/SideMenuViewController.swift, Permanent/ViewModels/ArchivesViewModel.swift, Permanent/ViewModels/AuthViewModel.swift
As a user I should be able to setup my archive legacy planning by going into the left menu, expanding the Archive Settings and Tapping on the Configure Legacy Steward.
=> VSP-1146 [iOS] Add button in Archive Settings that takes you to the Archive Legacy Planning

Permanent.xcodeproj/project.pbxproj, Permanent/Assets/Assets.xcassets/Images/editIcon.imageset/Contents.json, Permanent/Models/Data/ArchiveVO.swift, Permanent/Storyboards/LegacyPlanning.storyboard, Permanent/ViewControllers/LegacyPlanning/Cells/LegacyAccountStatusCell.xib, Permanent/ViewControllers/LegacyPlanning/Cells/LegacyArchiveCompletedCell.swift, Permanent/ViewControllers/LegacyPlanning/Cells/LegacyArchiveCompletedCell.xib, Permanent/ViewControllers/LegacyPlanning/Cells/LegacyArchiveCreateCell.swift, Permanent/ViewControllers/LegacyPlanning/Cells/LegacyArchiveCreateCell.xib, Permanent/Views/Cells/ShareManagementCollectionViewCells/ShareManagementDefaultAccessRoleCollectionViewCell.xib, Permanent/Views/Cells/ShareManagementCollectionViewCells/ShareManagementSharedWithCollectionViewCell.xib, Permanent/Views/RoundedImageView.swift
Make editImage template in order to be reusable
Add rounded corners to archive thumbnail and use that on the status page
=> Fix fonts on the status screen

.github/workflows/buildTestFlight.yml, Permanent/Models/Data/LegacyPlanning/LegacyPlanningSteward.swift, Permanent/Storyboards/LegacyPlanning.storyboard, Permanent/ViewControllers/LegacyPlanning/Cells/LegacyAccountStatusCell.swift, Permanent/ViewControllers/LegacyPlanning/ViewController/LegacyPlanningStewardViewController.swift, Permanent/ViewControllers/LegacyPlanning/ViewController/TrustedStewardViewController.swift, Permanent/ViewControllers/LegacyPlanning/ViewModels/LegacyPlanningViewModel.swift, Permanent/Views/Banner/BannerType.swift, Permanent/Views/Banner/BannerView.swift
Also disable the release branch builds until we find a fix
=> Fix texts based on feedback

Permanent.xcodeproj/project.pbxproj, Permanent/Common/Base/Views/FlowGrid.swift, Permanent/Common/Constants/Colors.swift, Permanent/Common/Extensions/TextExtension.swift, Permanent/Common/ViewModifiers/TextViewModifiers.swift, Permanent/Modules/EditMetadata/Views/TagsView.swift, Permanent/Resources/Assets/Assets.xcassets/Colors/IndianSaffron.colorset/Contents.json
=> Add Tags View

Permanent/Common/Base/SwiftUINavigationViews/CustomNavigationView.swift, Permanent/Common/Base/TextViews/TextViewUIRepresentable.swift, Permanent/Common/Models/Data/Folder/MinFolderVO.swift, Permanent/Modules/EditMetadata/ViewModels/FilesMetadataViewModel.swift, Permanent/Modules/EditMetadata/Views/MetadataEditView.swift, Permanent/Modules/EditMetadata/Views/TagsView.swift, Permanent/ViewModels/ViewModel/FileModel.swift
Fixed the following issues:
- Navigation bar changes to white color when you scroll in metadata edit screen
- Error is not shown when we are unable to save description
- "Add tag" button doesn't appear in tags list
=> VSP-937-2 [iOS] Resolve bugs observed at previous demo session

Permanent.xcodeproj/project.pbxproj, Permanent/Models/Data/MinArchiveVO.swift, Permanent/ViewControllers/FileMenuViewController.swift, Permanent/ViewControllers/MainViewController.swift, Permanent/ViewControllers/Profile/PublicArchiveFileViewController.swift, Permanent/ViewControllers/SearchViewController.swift, Permanent/ViewControllers/SharesViewController.swift, Permanent/ViewModels/UI/FileViewModel.swift, Permanent/Views/Cells/FileCollectionViewCell.swift, Permanent/Views/File Browsing/FolderContentView.swift
Fixed an issue where creating a new folder didn't let the user navigate to it.
=> VSP-1238 [iOS] Fix thumb status issue

Permanent/Common/Network/FilesEndpoint.swift, Permanent/Modules/EditMetadata/ViewModels/MetadataEditFileNamesViewModel.swift, Permanent/Modules/EditMetadata/Views/MetadataEditFileNamesView.swift
Added API call for changing the filename in edit metadata for replace and append.
=> VSP-939 [iOS] Edit Files Metadata - File Names: Replace

Permanent/Common/Base/SwiftUIViews/RightButtonView.swift, Permanent/Common/Base/SwiftUIViews/SectionView.swift, Permanent/Common/Constants/Colors.swift, Permanent/Common/Network/TagEndpoint.swift, Permanent/Modules/EditMetadata/ViewModels/AddNewTagViewModel.swift, Permanent/Modules/EditMetadata/ViewModels/FilesMetadataViewModel.swift, Permanent/Modules/EditMetadata/Views/MetadataEditView.swift, Permanent/Modules/EditMetadata/Views/TagsView.swift
Resolved minor issues and added new UI elements to edit metadata view :
- text: "Some files already have description!"
- new button: "Apply all to selection"
=> VSP-1224 [iOS] Delete Tag + Apply Tags to all

Permanent/Common/Base/SwiftUIViews/PullDownButton.swift, Permanent/Modules/EditMetadata/ViewModels/AppendFilenameViewModel.swift, Permanent/Modules/EditMetadata/ViewModels/SequenceFilenameViewModel.swift, Permanent/Modules/EditMetadata/Views/AppendFilenameView.swift, Permanent/Modules/EditMetadata/Views/SequenceFilenameView.swift, Permanent/ViewModels/ViewModel/FileModel.swift
- Updated the UI for the sequence edit tab in the metadata edit tab
- Implemented file name change for sequence edit.
- Added new implementation for filenames sequence edit, that will help in adding a date or a number.
=> VSP-949[iOS] Edit Files Metadata - File Names: Sequence

Permanent.xcodeproj/project.pbxproj, Permanent/Common/Base/SwiftUIViews/CustomAlertView.swift, Permanent/Common/Extensions/ViewExtension.swift, Permanent/Common/ViewModifiers/TextViewModifiers.swift, Permanent/Modules/EditMetadata/ViewModels/EditDateAndTimeViewModel.swift, Permanent/Modules/EditMetadata/Views/EditDateAndTimeView.swift, Permanent/Modules/EditMetadata/Views/MetadataEditView.swift
Added new confirmation dialog.
=> VSP-941[iOS] Edit Files Metadata - Date & Time

Permanent/Modules/Main/ViewController/MainViewController.swift, Permanent/Modules/UploadManager/ViewModels/UploadManagerViewModel.swift, Permanent/Modules/UploadManager/Views/UploadManagerView.swift
- Added upload button action for selected files.
- Resolved update number of files bug.
=> VSP-1201 [iOS] Upload Files from App #2

Permanent/Modules/Shares/ViewController/SharesViewController.swift, Permanent/Modules/UploadManager/ViewModels/UploadManagerViewModel.swift
- Added the new enhanced upload to shared files and public files.
- Resolved a bug where the current folder name is incorrectly displayed in the enhanced upload screen.
=> VSP-1322 [iOS] Upload files from app - Share + Public

Permanent/Common/Base/SwiftUIViews/ChipView/EmailChipView.swift, Permanent/Common/Extensions/IntExtension.swift, Permanent/Modules/GiftStorage/ViewModels/GiftStorageViewModel.swift, Permanent/Modules/GiftStorage/Views/GiftStorageView.swift
Added error handling for different scenarios involving total space needed for gifting.
=> VSP-1323 [iOS] Gifting - Gift Amount + Note

Permanent.xcodeproj/project.pbxproj, Permanent/Common/Base/SwiftUIViews/ChipView/EmailChipView.swift, Permanent/Common/Extensions/ViewExtension.swift, Permanent/Common/Models/Data/Billing/GiftingModel.swift, Permanent/Common/Network/BillingEndpoint.swift, Permanent/Modules/GiftStorage/ViewModels/GiftStorageViewModel.swift, Permanent/Modules/GiftStorage/Views/GiftStorageView.swift, Permanent/Modules/SideMenus/ViewController/RightSideMenuViewController.swift
Added new animation for scrolling to the bottom when writing a note.
=> VSP-1330 [iOS] Gifting send gift storage

Permanent/Modules/GiftStorage/ViewModels/GiftStorageViewModel.swift, Permanent/Modules/GiftStorage/Views/GiftStorageView.swift, Permanent/Modules/SideMenus/ViewController/RightSideMenuViewController.swift, Permanent/Modules/Storage/DonateViewController.swift, Permanent/Modules/Storage/DonateViewModel.swift, Permanent/Resources/Assets/Localization/en.lproj/Localizable.strings, Permanent/Resources/Storyboards/Donate.storyboard
Removed anonymous checkmark in the add storage menu
Resolved other minor issues
=> VSP-1332 [IOS] Remove the "Make my purchase anonymous" at storage checkout

Permanent.xcodeproj/project.pbxproj, Permanent/Common/Network/ArchivesEndpoint.swift
Added archive type to the sent parameters for profile thumbnail update.
=> VSP-1387 [IOS] Archive profile photo and banner can't be changed

Permanent/Common/Files/ViewModel/MyFilesViewModel.swift, Permanent/Modules/FileOperations/Cells/FileCollectionViewHeaderCell.swift, Permanent/Modules/Main/ViewController/MainViewController.swift, Permanent/Modules/PublicProfile/ViewController/PublicArchiveViewController.swift
Resolved a bug, where the select button was present when selecting a profile thumbnail.
=> VSP-1387[IOS]Archive profile photo and banner can't be changed

Permanent/Common/Models/Enums/ArchiveType.swift, Permanent/Modules/Onboarding/Views/OnboardingSelectArchiveTypeView.swift
Resolved issues that were found during testing.
=> VSP-1393 [IOS][Tablet] Create your first archive - Select Archive

Permanent.xcodeproj/project.pbxproj, Permanent/Common/Base/SwiftUIViews/SectionView.swift, Permanent/Common/Base/SwiftUIViews/SnackBarView.swift, Permanent/Modules/EditMetadata/ViewModels/FilesMetadataViewModel.swift, Permanent/Modules/EditMetadata/Views/MetadataEditView.swift
https://github.com/PermanentOrg/permanent-ios/assets/132879818/430dbd90-b1a2-4ec8-ab74-d220bb847b6d
=> Add loading indicator while gathering metadata

Permanent.xcodeproj/project.pbxproj, Permanent/Common/Base/SwiftUIViews/ButtonViews/SmallRoundButtonImageView.swift, Permanent/Common/Base/TextFields/CustomBorderTextField.swift, Permanent/Common/Extensions/TextField+Extension.swift, Permanent/Common/Extensions/ViewExtension.swift, Permanent/Common/ViewModifiers/TextViewModifiers.swift, Permanent/Modules/Onboarding/ViewModel/OnboardingStorageValues.swift, Permanent/Modules/Onboarding/Views/OnboardingArchiveName.swift, Permanent/Modules/Onboarding/Views/OnboardingCreateFirstArchiveView.swift, Permanent/Modules/Onboarding/Views/OnboardingView.swift, Permanent/Modules/Onboarding/Views/OnboardingWelcomeView.swift
Added a view for entering archive name, for both types of devices.
=> VSP-1369[IOS][Phone] Create your first Archive - Enter Archive Name

Permanent/Modules/Onboarding/Views/OnboardingChartYourPathView.swift, Permanent/Modules/Onboarding/Views/PathItemView.swift
Added a new screen for onboarding, here the user can select multiple choices for the current archive path.
=> VSP-1371 [IOS][Tablet] Chart your path

Permanent.xcodeproj/project.pbxproj, Permanent/Common/Base/SwiftUIViews/ButtonViews/GradientArchiveButtonView.swift, Permanent/Common/Base/SwiftUIViews/LabelViews/CustomTextLabel.swift, Permanent/Common/Base/SwiftUIViews/LoadingAnimations/GradientSemiCirclesLoaderView.swift, Permanent/Common/Constants/Colors.swift, Permanent/Common/Models/Enums/ArchiveType.swift, Permanent/Modules/Authentication/ViewController/LoginViewController.swift, Permanent/Modules/Authentication/ViewController/SignUpViewController.swift, Permanent/Modules/Onboarding/ViewModel/OnboardingArchiveViewModel.swift, Permanent/Modules/Onboarding/ViewModel/OnboardingStorageValues.swift, Permanent/Modules/Onboarding/Views/OnboardingArchiveName.swift, Permanent/Modules/Onboarding/Views/OnboardingChartYourPathView.swift, Permanent/Modules/Onboarding/Views/OnboardingCreateFirstArchiveView.swift, Permanent/Modules/Onboarding/Views/OnboardingItemView.swift, Permanent/Modules/Onboarding/Views/OnboardingSelectArchiveTypeView.swift, Permanent/Modules/Onboarding/Views/OnboardingView.swift, Permanent/Modules/Onboarding/Views/OnboardingWelcomeView.swift, Permanent/Modules/Onboarding/Views/OnboardingWhatsImportantView.swift
- Added API calls to create the archive after onboarding.
- Added new custom animation for loading
- Resolved some bugs on Create your archive View where the archive type button was small on different screen sizes
=> VSP-1409 [iOS][Tablet]Save onboarding data to the server

Permanent/Common/Base/SwiftUIViews/LabelViews/CustomTextLabel.swift, Permanent/Common/Models/Enums/ArchiveType.swift, Permanent/Common/Models/Enums/OnboardingPath.swift, Permanent/Common/Models/Enums/OnboardingWhatsImportant.swift, Permanent/Common/Network/AccountEndpoint.swift, Permanent/Modules/Onboarding/ViewModel/OnboardingArchiveViewModel.swift
Added new request for sending archive tags.
=> VSP-1421[IOS] Mailchip implementation

Permanent/Modules/Archives/ViewController/ArchivesViewController.swift
Non-profit archive type was removed from Create new archive.
=> VSP-1435[IOS] Remove nonprofit archive type from archive creation selector

Permanent/Modules/Onboarding/Screens/ArchiveName/OnboardingArchiveNameView.swift, Permanent/Modules/Onboarding/Screens/CreateArchive/OnboardingCreateFirstArchiveView.swift, Permanent/Modules/Onboarding/Screens/WhatsImportant/OnboardingWhatsImportantViewModel.swift
Resolved bugs from testing this ticket.
=> VSP-1428 [IOS] Onboarding design updates resolved testing bugs

Permanent/Modules/Authentication/Screens/LoginView.swift, Permanent/Modules/Authentication/Views/CustomLoginFormView.swift, Permanent/Modules/Authentication/Views/ErrorBannerView.swift
Resolved font issues found on testing
Changed text from "Register" to "Sign Up"
=> VSP-1442 [IOS][Mobile]Login Screen #2 fixed founded bugs

Permanent.xcodeproj/project.pbxproj, Permanent/Modules/Authentication/Screens/Container/AuthenticatorContainerView.swift, Permanent/Modules/Authentication/Screens/Container/AuthenticatorContainerViewModel.swift, Permanent/Modules/Authentication/Screens/ForgotPassword/ForgotPasswordConfimationView.swift, Permanent/Modules/Authentication/Screens/ForgotPassword/ForgotPasswordView.swift, Permanent/Modules/Authentication/Screens/ForgotPassword/ForgotPasswordViewModel.swift, Permanent/Modules/Authentication/Screens/Login/LoginView.swift, Permanent/Modules/Authentication/Screens/VerifyIdentity/AuthVerifyIdentityViewModel.swift, Permanent/Modules/Authentication/Views/CustomForgotPasswordFieldView.swift
Added forgot password screen for iPhone.
=> VSP-1441 [IOS][Mobile] Forgot password

Permanent/Modules/Authentication/Screens/ForgotPassword/ForgotPasswordView.swift
=> VSP-1452 [IOS][Tablet] Forgot password

Permanent/Modules/Authentication/Screens/Container/AuthenticatorContainerView.swift, Permanent/Modules/Authentication/Screens/Login/LoginView.swift, Permanent/Modules/Authentication/Screens/VerifyIdentity/AuthVerifyIdentityView.swift, Permanent/Modules/Authentication/Screens/VerifyIdentity/AuthVerifyIdentityViewModel.swift, Permanent/Modules/Authentication/Views/AuthBannerView.swift, Permanent/Modules/Authentication/Views/Login2FAFieldView.swift
We have resolved some issues regarding the keyboard appearing/disappearing when we enter the four-digit code.
=> VSP-1452 [IOS][Tablet] Verify identity Vies issue 

Permanent.xcodeproj/project.pbxproj, Permanent/Common/Authentication/ViewModel/AuthViewModel.swift, Permanent/Common/Managers/AuthenticationManager.swift, Permanent/Common/Network/AccountEndpoint.swift, Permanent/Modules/AccountSettings/ViewController/AccountDeleteViewController.swift, Permanent/Modules/AccountSettings/ViewController/AccountInfoViewController.swift, Permanent/Modules/AccountSettings/ViewModel/AccountDeleteViewModel.swift, Permanent/Modules/Authentication/Screens/Container/AuthenticatorContainerViewModel.swift, Permanent/Modules/Authentication/Screens/Register/RegisterView.swift, Permanent/Modules/Authentication/Screens/Register/RegisterViewModel.swift, Permanent/Modules/Authentication/ViewController/SignUpViewController.swift, Permanent/Modules/Main/Navigation/Routers/SettingsRouter.swift, Permanent/Services/Repositories/AccountRepository.swift, Permanent/Services/Repositories/Datasources/Remote/AccountRemoteDataSource.swift
New design was added to the Register account.
Also resolved the issue where the delete account operation didn't function correctly.
=> [IOS] Register account - API

Permanent/Modules/Authentication/ViewController/BiometricsViewController.swift, Permanent/Modules/Authentication/Views/AuthImageForRightSidePageView.swift, Permanent/Resources/Assets/Assets.xcassets/Images/Authentication/authSignInLeftImage.imageset/Contents.json, Permanent/Resources/Storyboards/Authentication.storyboard
Added constraints for iPad screen.
Here is a preview:
=> VSP-1470[IOS][Tablet] Face ID screen redesign

Permanent/Common/Constants/Constants.swift, Permanent/Modules/AccountSecurity/Views/TwoStepVerificationView.swift, Permanent/Modules/Authentication/Screens/Login/LoginViewModel.swift, Permanent/Modules/SideMenus/ViewModels/SettingsScreenViewModel.swift, Permanent/Modules/SideMenus/Views/SettingsScreenView.swift
The following issues were resolved:
- Phone number not displayed correctly
- Loading the 2FA status in the settings menu
=> VSP-1508 [IOS] Warning icon should appear only when 2FA is disabled

Permanent/Modules/Main/ViewController/MainViewController.swift
Resolved the refresh files workspace after switching the archive.
=> VSP-1513 [iOS] Archive contents do not update when changing archives

Permanent/App/AppDelegate.swift, Permanent/Common/Network/APIErrors.swift, Permanent/Common/Network/ShareEndpoint.swift
Resolved the issue with the invitation link not working
Changed the message when a new member without a Permanent account was added.
=> VSP-1524 iOS share link from email notification opens error page

Permanent/Modules/Authentication/Views/TopBannerView.swift
Updated maintenance banner message.
=> VSP-1515 Downtime banner for postgre/fusionauth update #2

Permanent.xcodeproj/project.pbxproj, Permanent/Common/Models/Enums/AuthBannerMessage.swift, Permanent/Common/Network/AuthenticationEndpoint.swift, Permanent/Modules/AccountSecurity/Models/TwoFactorMethod.swift, Permanent/Modules/AccountSecurity/ViewModel/TwoStepChooseEmailViewModel.swift, Permanent/Modules/AccountSecurity/ViewModel/TwoStepChoosePhoneViewModel.swift, Permanent/Modules/AccountSecurity/ViewModel/TwoStepConfirmPasswordViewModel.swift, Permanent/Modules/AccountSecurity/ViewModel/TwoStepConfirmationContainerViewModel.swift, Permanent/Modules/AccountSecurity/ViewModel/TwoStepVerificationViewModel.swift, Permanent/Modules/AccountSecurity/Views/DeleteBottomAlertView.swift, Permanent/Modules/AccountSecurity/Views/RoundButtonUsualBlue50View.swift, Permanent/Modules/AccountSecurity/Views/TwoStepBottomNotificationView.swift, Permanent/Modules/AccountSecurity/Views/TwoStepChooseEmailView.swift, Permanent/Modules/AccountSecurity/Views/TwoStepChoosePhoneView.swift, Permanent/Modules/AccountSecurity/Views/TwoStepConfirmationContainerView.swift, Permanent/Modules/AccountSecurity/Views/TwoStepVerificationView.swift
Added the functionality to remove 2FA for email and sms methods.
https://github.com/user-attachments/assets/344e35ce-9593-4d60-9554-abf37ff02554
=> VSP-1529 [IOS][Mobile] 2FA - Delete email

Permanent.xcodeproj/project.pbxproj, Permanent/Modules/AccountSecurity/ViewModel/TwoStepChooseEmailViewModel.swift, Permanent/Modules/AccountSecurity/ViewModel/TwoStepChoosePhoneViewModel.swift, Permanent/Modules/AccountSecurity/ViewModel/TwoStepConfirmationContainerViewModel.swift, Permanent/Modules/AccountSecurity/ViewModel/TwoStepVerificationViewModel.swift, Permanent/Modules/AccountSecurity/Views/BannerBottomMessage.swift, Permanent/Modules/AccountSecurity/Views/BottomNotificationWithOverlayView.swift, Permanent/Modules/AccountSecurity/Views/ChangeAuthMethodBottomAlertView.swift, Permanent/Modules/AccountSecurity/Views/TwoStepConfirmationContainerView.swift, Permanent/Modules/AccountSecurity/Views/TwoStepVerificationView.swift
We have added new functionality for changing the 2fa method, which consists of deleting and adding together, which were already implemented.
https://github.com/user-attachments/assets/0e6fdf84-6259-4287-9fbb-4172f3cd262c
=> VSP-1534[IOS][Mobile] 2FA - Change Verification Method

Permanent.xcodeproj/project.pbxproj, Permanent/App/AppDelegate.swift, Permanent/Common/Helpers/NetworkLogger.swift, Permanent/Common/Managers/Upload/UploadManager.swift, Permanent/Common/Managers/Upload/UploadOperation.swift, Permanent/Modules/Main/Navigation/Routers/SettingsRouter.swift
Changed minimum support version to iOS 16.6
Modified upload of multiple files to dynamically adjust the number of simultaneous uploaded files regarding network upload speed. 
Added detent for settings view.
Added a new logging system.
Preview for upload with a good/bad connection:
https://github.com/user-attachments/assets/7aa1e394-b230-43be-8b89-77205dda3938
https://github.com/user-attachments/assets/b3eae558-9ac5-4f63-9736-b206209bd98a
=> VSP-1536 [IOS][Tablet] Account Setting Menu

Permanent/Common/Base/UIKitViews/FABView.swift, Permanent/Common/Constants/Constants.swift, Permanent/Common/Managers/AuthenticationManager.swift, Permanent/Resources/Assets/Assets.xcassets/Images/whiteArrowView.imageset/Contents.json, Permanent/Resources/Assets/Assets.xcassets/Images/whiteArrowView.imageset/whiteArrowView.svg
[Added member checklist banner for 3 seconds.
=> VSP-1561 [IOS][Mobile] Add member checklist alert

Permanent.xcodeproj/project.pbxproj, Permanent/Modules/LegacyPlanning/ViewController/LegacyPlanningStewardViewController.swift, Permanent/Modules/Main/Navigation/ChecklistCoordinator.swift, Permanent/Modules/Main/ViewModel/ChecklistOptionsViewModel.swift, Permanent/Modules/Main/Views/ChecklistBottomMenuView.swift, Permanent/Modules/Main/Views/ChecklistOptionsView.swift, Permanent/Resources/Storyboards/LegacyPlanning.storyboard
Added navigation to first 3 items from members checklist.
Preview: 
https://github.com/user-attachments/assets/f3a5846f-dd2c-4fd3-b6ad-cb6b80a7d9e2
=> VSP-1578 [iOS] New member checklist - Navigation Part 1 
