PermanentOrg/permanent-ios

- Permanent.xcodeproj/project.pbxproj
- Permanent/ViewControllers/FileDetailsViewController.swift
- Permanent/ViewControllers/FilePreviewNavigationController.swift
- Permanent/ViewControllers/FilePreviewViewController.swift
- Permanent/ViewControllers/MainViewController.swift
- Permanent/ViewControllers/SharesViewController.swift
- Permanent/Views/Cells/FileDetailsCollectionViewCells/FileDetailsTopCollectionViewCell.swift
- Permanent/Views/Cells/FileDetailsCollectionViewCells/FileDetailsTopCollectionViewCell.xib
- created custom navigation controller for file preview screens
- file preview navigation has delegate to main/shares screen
- file details notifies file preview navigation when a change occured
- file preview navigation notifies main/shares when a change occured in order to reload data.
- file preview and file details now share the same instance of view model, in order to reduce loading time when navigating between the two screens
> VSP-246 [iOS] After editing a file's meta data, when returning back to the list of files refresh the page

- Permanent/Storyboards/Main.storyboard
- Permanent/ViewControllers/FileDetailsViewController.swift
- Permanent/ViewControllers/TagDetailsViewController.swift
- Permanent/Views/Cells/FileDetailsCollectionViewCells/TagsNamesCollectionViewCell.swift
- Permanent/Views/Cells/FileDetailsCollectionViewCells/TagsNamesCollectionViewCell.xib
The following were implemented : 
- [iOS] Tag section height is not correct for long tags in the File Details Screen
- [iOS] Show all tags in meta data detail page
- Added a maximum limit of 24 characters for tag name.
> VSP-296 [iOS] Tag section height is not correct for long tags in the File Details Screen

- Permanent.xcodeproj/project.pbxproj
- Permanent/ViewControllers/FileDetailsViewController.swift
- Permanent/ViewControllers/TagDetailsViewController.swift
In file details, fixed the issue that showed the spinning cycle when wanted to add tags but none were present.
> VSP-414 [iOS] The spinner on the Edit Tags screen isn't dismissed if there are no tags available in the archive

- Permanent.xcodeproj/project.pbxproj
- Permanent/AppDelegate.swift
- Permanent/Models/Data/BaseNotificationPayload.swift
- Permanent/Models/Data/PARequestNotificationPayload.swift
- Permanent/Models/Data/RequestLinkAccessNotificationPayload.swift
- Permanent/Models/Data/ShareNotificationPayload.swift
- Permanent/ViewControllers/MainViewController.swift
- Permanent/ViewControllers/MembersViewController.swift
- Permanent/ViewControllers/RootViewController.swift
- Permanent/ViewControllers/SharesViewController.swift
- Permanent/ViewModels/FilesViewModel.swift
- Permanent/ViewModels/MembersViewModel.swift
AppDelegate
- saved new fields in the notification payload
- fixed incorrect constant names when clearing deeplinks
- removed some navigation logic that was moved to the corresponding controllers
MainVC
- removed unused function checkForSavedShareFile
- added alert to switch archive
MembersVC
- added alert to swtich archive
RootVC
- moved some of the logic here in the corresponding controllers
SharesVC
- added alert to switch archive
- added logic to navigate to the correct file/folder based on the notification payload
FilesVM
- added api call to change archive
MembersVM
- added api call to change archive
> [iOS] As a user I want to swap to the correct archive when I receive a push notification

- Permanent/Constants/Constants.swift
- Permanent/ViewControllers/SplashViewController.swift
- Permanent/ViewModels/AuthViewModel.swift
- add model version storage
- check the version before authentication in order to logout the user if they have a previous version of the model
- save model version after a successful login
> VSP-528 Add migration for multiple archives model

- Permanent/Scenes/Share Preview/ViewControllers/SharePreviewViewController.swift
- Permanent/Scenes/Share Preview/ViewModels/SharePreviewViewModel.swift
- Permanent/Scenes/Share Preview/ViewModels/SharePreviewViewModelDelegate.swift
- Permanent/ViewControllers/ArchivesViewController.swift
- Permanent/ViewModels/ArchivesViewModel.swift
Implemented hide "Change archive" button in Share preview screen if the user have only one archive.
> VSP-545 [iOS] When having a single archive, do not show change archive button in Share Preview Screen

- Permanent/ViewControllers/FileDetailsViewController.swift
- Permanent/ViewControllers/FilePreviewListViewController.swift
- Permanent/ViewControllers/FilePreviewViewController.swift
- Permanent/ViewControllers/MainViewController.swift
- Permanent/ViewModels/FilesViewModel.swift
Added both file share methods("Share to Another App" and "Share in Permanent") in file manager, file viewer and file details viewer.
Changed "Share" icon from top right in file viewer and file details viewer to "More" icon
> [iOS] Get the Permanent share menu into the share sheet

- Permanent/Managers/Upload/UploadOperation.swift
- Permanent/Views/Cells/FileDetailsCollectionViewCells/FileDetailsDateCollectionViewCell.swift
Updated the date sent to the RegisterRecord API so that it's a UTC date, since the server ignores the timezone in the date field.
Updated the UI to display the Timezone
> Vsp 486 Uploaded / last modified time shows UTC time rather than local time

- Permanent/Models/Data/ShareVO.swift
- Permanent/Models/Payloads.swift
- Permanent/Network/APIErrors.swift
- Permanent/Network/AccountEndpoint.swift
- Permanent/Storyboards/Share.storyboard
- Permanent/ViewControllers/ShareViewController.swift
- Permanent/ViewModels/ShareLinkViewModel.swift
- Permanent/Views/Cells/ArchiveTableViewCell/ArchiveTableViewCell.swift
- Permanent/Views/Cells/ArchiveTableViewCell/ArchiveTableViewCell.xib
- Modified accept/deny share request endpoints to be able to use them for update/delete share request methods.
- Add sharing management to the share modal – remove, change perms, etc. before full release
- Added UI to manage sharing permissions
- Added api response notifications.
- Added refresh metod on deny action.
> VSP-508 [iOS] Add sharing management to the share modal – remove, change perms, etc. before full release

- Permanent/ViewControllers/FileDetailsViewController.swift
- Permanent/ViewControllers/FilePreviewViewController.swift
- Permanent/ViewControllers/MainViewController.swift
- Changed share file text to : "Share via permanent" [VSP-597]
- Fixed "Share via Permanent" option so that will not be displayed when current archive role is different than owner
> VSP-595 [iOS] Sharing shares permission management - Should only be enabled for owners

- Permanent/ViewControllers/ArchivesViewController.swift
Added height attribute to TableView Header.
> VSP-601 [iOS] First archive in the Manage Archives Screen is cutoff at the top

- Permanent/Constants/Constants.swift
- Permanent/Models/APIPayload.swift
- Permanent/Models/Payloads.swift
- Removed API Key from the Constants file
- Removed API Key from all Payloads
- Improved handling of csrf, as the runtime would sometimes get confused on the type of the saved value
> VSP-609 [iOS] Remove Permanent API key

- Permanent/Assets/Localization/en.lproj/Localizable.strings
- Permanent/ViewControllers/Authentication/CodeVerificationController.swift
- Removed pin limit in the Verification Screen
- Adjusted the text to no longer mention how many digits the code has
> VSP-613 [iOS] Remove pin length limit

- Permanent/ViewControllers/FilePreviewViewController.swift
- Permanent/ViewModels/FilePreviewViewModel.swift
- Added configuration for the AVAudioSession when the File Preview screen loads
- Removed private option from the AVURLAsset
- Refactored code in the ViewModel so that it asks the Apple SDK for playback ability. It will switch to the converted file only if the SDK says that the default file is not playable
> VSP-615 [iOS] Video has no sound

- Permanent/Models/Payloads.swift
- Permanent/Network/AccountEndpoint.swift
- Permanent/Storyboards/Settings.storyboard
- Permanent/ViewControllers/AccountInfoViewController.swift
- Permanent/ViewModels/InfoViewModel.swift
- added second address line in account info (storyboard, and view controller)
- improved the view model logic:
- csrf logic was fixed a while ago, so there's no need to do an update to the csrf token
- the accountId can live in the viewModel, no need to pass it between the controller and the vm
- removed unused view model code
- linted all files that were touched
> VSP-505 [iOS] Address should have two fields in Account Info

- Permanent.xcodeproj/project.pbxproj
- Permanent/AppDelegate.swift
- Permanent/Models/DrawerOption.swift
- Permanent/ViewControllers/FilePreviewListViewController.swift
- Permanent/ViewControllers/MainViewController.swift
- Permanent/ViewControllers/RootViewController.swift
- Permanent/ViewControllers/SideMenuViewController.swift
- Permanent/ViewModels/PublicFilesViewModel.swift
- adapted the mainVC to support both MyFiles and MyPublicFiles
- it now requires a ViewModel at the time of instantiation, based on this it can either display private or public files
- added alert when uploading to the public workspace
- added a new file option to share public files
- linted the file
- temporarily added a link to the Public Files
- this whole UI will be refreshed next sprint
- linted the file
- instantiated the appropriate ViewModel for the MainVC
- overriden methods needed for the public workspace navigation
- added handling for the public files when opened from the public files workspace
- linted the file
> VSP-630 [iOS] Public Files Screen

- Permanent/Constants/Strings.swift
- Permanent/Managers/FileAction.swift
- Permanent/ViewControllers/MainViewController.swift
- Podfile.lock
- Removed Copy dialog box
- Changed "Move","Copy" to "Paste" button in the bottom right part of the screen when a file was copied
> VSP-466 [iOS] Copy requires 2 confirmation steps

- Permanent/ViewControllers/FilePreviewViewController.swift
- Fixed a bug that crashed the app when taping a shared item notification.
- Resolved SwiftLint warnings for modified file.
> VSP-670 [iOS] Crashed on clicking notification that [archive] has shared with you.

- Permanent/Network/APIErrors.swift
- Permanent/ViewControllers/BaseViewController.swift
- Permanent/ViewControllers/MainViewController.swift
- Permanent/ViewControllers/MembersViewController.swift
- Permanent/ViewControllers/SharesViewController.swift
- Permanent/ViewModels/MembersViewModel.swift
- Permanent/ViewModels/UI/FileListType.swift
- Permanent/Views/ActionDialogView/ActionDialogStyle.swift
- Permanent/Views/ActionDialogView/ActionDialogView.swift
- Permanent/Views/Cells/FileDetailsCollectionViewCells/FileDetailsBaseCollectionViewCell.swift
- Permanent/Views/Cells/FileDetailsCollectionViewCells/FileDetailsBottomCollectionViewCell.xib
- Permanent/Views/Share Link/InputSettingsView.swift
- Update error message when adding a member that already has access [VSP-392]
- Description field defaults to lowercase [VSP-472]
- Adding a member should pop up the email keyboard [VSP-500]
- When editing settings for a share link, the expiration date has "cancel" and "done" reversed from where I expected them to be. Done is on the left and Cancel is on the right [VSP-671]
- When downloading an image, you tap download and then it does happen, but there's no confirmation on the Permanent app that anything happened. It'd be nice if there was confirmation that it downloaded [VSP-672]
- Resolved SwiftLint warnings for modified files
> VSP-392 [iOS] Update error message when adding a member that already has access

- Permanent/Storyboards/Archives.storyboard
- Permanent/ViewControllers/ArchivesViewController.swift
- Permanent/ViewControllers/MainViewController.swift
- Permanent/Views/ActionDialogView/ActionDialogView.swift
- Fixed notification message when successful rename file/folder
- Added file/folder name in the edit field when renaming, in case the user just wants to make a small change
- Removed the step when the user had to press the additional done button in changing archive screen for a share link
- Removed bottom white space when changing archives for a share link.
> VSP-673 [iOS] Message on rename is incorrect.

- Permanent/Assets/Localization/en.lproj/Localizable.strings
- Permanent/Models/DrawerOption.swift
- Permanent/ViewControllers/AccountInfoViewController.swift
- Permanent/ViewControllers/ArchivesViewController.swift
- Permanent/ViewControllers/RightSideMenuViewController.swift
- Permanent/ViewControllers/SideMenuViewController.swift
- Changed "Next" button with "Done" for being able to dismiss the keyboard after the field was modified.
- Changed "Switch Archives" to "Archives"
- Removed "Archives" from left hand menu and added to right side menu, between "Activity Feed" and "Invitations" submenus.
- Changed "Account Info" to "Account"
> VSP-676 [iOS] Account Info: Allow editing of individual fields

- Permanent/ViewControllers/MainViewController.swift
- Permanent/ViewModels/FilesViewModel.swift
Fixed pull to refresh issue that refresh timer was not cancelled when user refreshed the folder manually.
> VSP-471 [iOS] Files which have finished processing are stuck with a spinner until manual refresh

- Permanent/Constants/Constants.swift
- Permanent/Managers/FileAction.swift
- Permanent/Models/Data/FileType.swift
- Permanent/Models/Data/MinArchiveVO.swift
- Permanent/Models/Enums/Permission.swift
- Permanent/ViewControllers/MainViewController.swift
- Permanent/ViewModels/MyFilesViewModel.swift
- Permanent/ViewModels/UI/FileState.swift
- Permanent/ViewModels/UI/FileStatus.swift
- Permanent/ViewModels/UI/FileViewModel.swift
- implemented Codable in FileAction and FileViewModel, and their dependencies 
- created storage keys for selected file action, and selected file
- saved/fetched the selected file and action from the shared preferences
> VSP-683  iOS: Copy files between Private Files and Public Files workspaces

- Permanent/Assets/Localization/en.lproj/Localizable.strings
- Permanent/Storyboards/Main.storyboard
- Permanent/Storyboards/Share.storyboard
Resolved the following issues:
- Folder title overlaps grid icon, for private, shared, public files and also for search files screen
- Change "browse" menu option to "browse files" when uploading a file.
> VSP-825 [iOS] Folder title overlaps grid icon

- Permanent.xcodeproj/project.pbxproj
- Permanent.xcodeproj/xcshareddata/xcschemes/Permanent.xcscheme
- PermanentUITests/LoginUITests.swift
- PermanentUITests/Pages/LeftSideMenu.swift
- PermanentUITests/Pages/LoginPage.swift
- PermanentUITests/Pages/PhotoLibraryPage.swift
- PermanentUITests/Pages/PrivateFilesPage.swift
- PermanentUITests/Pages/RightSideMenuPage.swift
- PermanentUITests/Pages/SharedFilesPage.swift
- PermanentUITests/Pages/SignUpPage.swift
- PermanentUITests/SharedFilesUITests.swift
- PermanentUITests/UploadFilesUITests.swift
Shared files menu test case should contain :
- login and navigate to private files screen
- navigate to Shared with me
- enter a folder with viewer permissions and test “+“ menu options
- enter a folder with owner permissions and test “+“ menu options
- log out from settings menu
> VSP-849 [iOS] UI test cases for shared files menu

- Permanent/Models/Data/MinArchiveVO.swift
- Permanent/ViewControllers/FileMenuViewController.swift
- Permanent/ViewControllers/MainViewController.swift
- Permanent/ViewControllers/SharesViewController.swift
- Permanent/ViewModels/ShareLinkViewModel.swift
- Permanent/ViewModels/SharedFilesViewModel.swift
- Permanent/Views/Cells/ArchiveTableViewCell/ArchiveTableViewCell.swift
Fixed the File Options Menu issue that didn't specify pending access with specific badge
Fixed changing the access role in "Share Management" does not update the access role badge
Fixed updating File Options Menu Shared with section after an archive rights were removed for current item.
> VSP-964 [iOS] File Options Menu: Changing the access role in "Share Management" does not update the access role badge

- Permanent/ViewControllers/Profile/PublicArchiveViewController.swift
- Permanent/ViewModels/PublicProfilePicturesViewModel.swift
Moved logic to the viewmodel
Changed the logic to look for "archiveShare" permission, instead of "ownership"
> Vsp 1049 Managers can't edit public profile photos

- .gitignore
- Permanent/Views/Cells/ShareManagementCollectionViewCells/ShareManagementAccessRolesCollectionViewCell.swift
Resolved the bug where the "Viewer" text from Share Access Roles sometimes is red.
> VSP-1050[iOS]Change Access Role screen displays roles as red, instead of black

- Permanent/ViewControllers/FileMenuViewController.swift
- Permanent/ViewControllers/MainViewController.swift
- Permanent/ViewControllers/SharesViewController.swift
Add an options menu for the selected items with the following options: 
- for private files and public files: copy move and delete
- for shared files: move and delete
> VSP-927 [iOS] Display options menu for multiple files

- Permanent.xcodeproj/project.pbxproj
- Permanent/Models/Data/LegacyPlanning/ArchiveSteward.swift
- Permanent/Models/Data/LegacyPlanning/StewardDetails.swift
- Permanent/Models/Repositories/Datasources/Remote/LegacyPlanningDataSourceInterface.swift
- Permanent/Storyboards/LegacyPlanning.storyboard
- Permanent/ViewControllers/ArchivesViewController.swift
- Permanent/ViewControllers/LegacyPlanning/ViewController/LegacyPlanningStewardViewController.swift
- Permanent/ViewControllers/LegacyPlanning/ViewController/TrustedStewardViewController.swift
- Permanent/ViewControllers/LegacyPlanning/ViewModels/LegacyPlanningViewModel.swift
- Remove email check and invitation screens (we can save these for later when we do have the capability to do the check and invite members)
- Add an error after saving the legacy plan if the steward doesn’t have an account
> VSP-1143 [IOS] Select archive Steward - Flow Changes

- Permanent.xcodeproj/project.pbxproj
- Permanent/Common/Base/SwiftUIViews/PullDownButton.swift
- Permanent/Modules/EditMetadata/ViewModels/AppendFilenameViewModel.swift
- Permanent/Modules/EditMetadata/ViewModels/MetadataEditFileNamesViewModel.swift
- Permanent/Modules/EditMetadata/ViewModels/ReplaceFilenameViewModel.swift
- Permanent/Modules/EditMetadata/ViewModels/SequenceFilenameViewModel.swift
- Permanent/Modules/EditMetadata/Views/AppendFilenameView.swift
- Permanent/Modules/EditMetadata/Views/CustomSegmentedControl.swift
- Permanent/Modules/EditMetadata/Views/MetadataEditFileNames.swift
- Permanent/Modules/EditMetadata/Views/MetadataEditFileNamesView.swift
- Permanent/Modules/EditMetadata/Views/MetadataEditView.swift
- Permanent/Modules/EditMetadata/Views/ReplaceFilenameView.swift
- Permanent/Modules/EditMetadata/Views/SequenceFilenameView.swift
- Permanent/ViewModels/ViewModel/FileModel.swift
Resolved a memory leak issue that appeared when replace, append, or sequence views were displayed.
Implemented preview filename for append view.
> VSP-939[iOS] Edit Files Metadata - File Names: Replace

- Permanent/App/AppDelegate.swift
- Permanent/Common/Base/SwiftUIViews/GradientCustomBarView.swift
- Permanent/Modules/SideMenus/ViewController/RightSideMenuViewController.swift
- Permanent/Modules/Storage/ViewModels/RedeemCodeViewModel.swift
- Permanent/Modules/Storage/ViewModels/StorageViewModel.swift
- Permanent/Modules/Storage/Views/RedeemCodeView.swift
- Permanent/Modules/Storage/Views/StorageView.swift
[Implemented remarks from the demo :
- Removed "free" and "complimentary" from redeem screen
- Round the amount of storage added by one decimal point(in GB)
Resolved a bug where the storage progress bar view would not update after a successful redeem code was added.
Also changed the path for the deep link to correspond with the real one.
> VSP-1364[iOS]Redeem code deep link and demo remarks implementations

- Permanent.xcodeproj/project.pbxproj
- Permanent/App/AppDelegate.swift
- Permanent/Common/Constants/Constants.swift
- Permanent/Modules/Main/ViewController/MainViewController.swift
- Permanent/Modules/Main/ViewController/NavigationController.swift
- Permanent/Modules/Shares/ViewController/SharesViewController.swift
- Permanent/Resources/Assets/Info.plist
The following were added:
- the application will be natively compatible with the iPad platform
- orientation lock
- a method that will help us identify the platform that the app is running on
- disable split view and slide over app mode
> VSP-1379[IOS] Add tablet support

- Permanent/Modules/PublicProfile/ViewController/PublicArchiveViewController.swift
Resolved another bug, where the changed archive thumbnail didn't change in the left and right menus only after a logout
> VSP-1387[iOS]Archive profile photo and banner can't be changed

- Permanent/Common/Files/ViewModel/MyFilesViewModel.swift
- Permanent/Modules/Main/ViewController/MainViewController.swift
- Permanent/Modules/PublicProfile/ViewController/PublicArchiveViewController.swift
Resolved another bug where you can't select a photo for a thumbnail, only view the file.
> VSP-1387[IOS] Archive profile photo and banner can't be changed

- Permanent/Modules/PublicProfile/ViewController/PublicArchiveViewController.swift
Changed the description text for the alert that changes the profile and banner picture.
> VSP-1387 [IOS] Archive profile photo and banner can't be changed

- Permanent/Modules/Shares/ViewController/SharesViewController.swift
Resolved an issue where the app tries to scroll to a null position in the collection view.
> VSP-1411 [IOS] Clicking on the View in archive from the Share Preview crashes the app

- Permanent.xcodeproj/project.pbxproj
- Permanent/Common/Extensions/StringExtension.swift
- Permanent/Common/Models/Enums/AuthBannerMessage.swift
- Permanent/Common/Network/AuthenticationEndpoint.swift
- Permanent/Modules/AccountSecurity/ViewModel/TwoStepChooseEmailViewModel.swift
- Permanent/Modules/AccountSecurity/ViewModel/TwoStepChoosePhoneViewModel.swift
- Permanent/Modules/AccountSecurity/ViewModel/TwoStepConfirmPasswordViewModel.swift
- Permanent/Modules/AccountSecurity/ViewModel/TwoStepConfirmationContainerViewModel.swift
- Permanent/Modules/AccountSecurity/Views/CustomEmailFieldView.swift
- Permanent/Modules/AccountSecurity/Views/CustomPhoneFieldView.swift
- Permanent/Modules/AccountSecurity/Views/TwoStepBottomNotificationView.swift
- Permanent/Modules/AccountSecurity/Views/TwoStepChooseEmailView.swift
- Permanent/Modules/AccountSecurity/Views/TwoStepChoosePhoneView.swift
- PermanentTests/AuthenticationManagerTests.swift
Added screens to add email and phone number methods to add 2FA.
Added send code API request.
Added bottom-screen notifications
Added resend timer.
> VSP-1485 [iOS] [Mobile] 2FA - Add Email - Send Code

- Gemfile
- Gemfile.lock
- Permanent/Modules/AccountSecurity/Views/LoginSecurityView.swift
- Permanent/Modules/Storage/Views/GiftStorageView.swift
- Resolved a bug where the buttons for adding storage as a gift didn't work.
- Removed the height of the submenus in the 2fa menu.
Preview:
https://github.com/user-attachments/assets/8c494ef3-a980-4973-a0b9-f44808d63c7a
> VSP-1548[IOS] Buttons/fields in gift storage modal not tappable

- Permanent/Common/Network/TagEndpoint.swift
Corrected a mismatch for the tag deletion functionality.
> VSP-1549[IOS] Cannot delete a tag in manage tags

- Permanent.xcodeproj/project.pbxproj
- Permanent/Common/Base/SwiftUINavigationViews/CustomNavigationView.swift
- Permanent/Common/Base/SwiftUINavigationViews/SimpleCustomNavigationView.swift
- Permanent/Common/Files/ViewModel/FilesViewModel.swift
- Permanent/Common/Helpers/ScrollViewAppearanceManager.swift
- Permanent/Common/Managers/AuthenticationManager.swift
- Permanent/Common/Models/Data/PublicProfile/ArchiveNameProfileItem.swift
- Permanent/Common/Models/Data/PublicProfile/ProfileItemVO.swift
- Permanent/Common/Models/Enums/ArchiveType.swift
- Permanent/Modules/Archives/Cells/ArchiveScreenChooseArchiveDetailsTableViewCell.xib
- Permanent/Modules/Archives/ViewController/ArchivesViewController.swift
- Permanent/Modules/Archives/ViewModel/ArchivesViewModel.swift
- Permanent/Modules/Main/Navigation/Routers/SettingsRouter.swift
- Permanent/Modules/Main/ViewController/MainViewController.swift
- Permanent/Modules/Main/ViewController/RootViewController.swift
- Permanent/Modules/ManageMembers/ViewModel/MembersViewModel.swift
- Permanent/Modules/Onboarding/Screens/Welcome/OnboardingInvitedWelcomeViewModel.swift
- Permanent/Modules/PublicProfile/Cells/ProfilePageAboutCollectionViewCell.swift
- Permanent/Modules/PublicProfile/Cells/ProfilePageAboutCollectionViewCell.xib
- Permanent/Modules/PublicProfile/Cells/ProfilePageFooterCollectionViewCell.xib
- Permanent/Modules/PublicProfile/Cells/ProfilePageInformationCollectionViewCell.xib
- Permanent/Modules/PublicProfile/ViewController/PublicArchiveFileViewController.swift
- Permanent/Modules/PublicProfile/ViewController/PublicArchiveViewController.swift
- Permanent/Modules/PublicProfile/ViewController/PublicProfileAboutPageViewController.swift
- Permanent/Modules/PublicProfile/ViewController/PublicProfilePageViewController.swift
- Permanent/Modules/PublicProfile/ViewModel/PublicProfilePageViewModel.swift
- Permanent/Modules/Shares/ViewController/SharesViewController.swift
- Permanent/Modules/SideMenus/Views/SettingsScreenView.swift
- Permanent/Resources/Storyboards/Profile.storyboard
Added Archive Profile Enhancements and UI Fixes
Key Changes:
- Added a new text field for changing archive name from Archive profile view
- Archive name changes are now reflected throughout the application
- Archive profile automatically reloads and scrolls to top when archive is changed
Bug Fixes:
- Fixed crash when changing archive while archive profile was selected
- Fixed FABview not showing after changing the archive
- Fixed size adjustment warning when entering ArchivesViewController
- Fixed RootViewController's landscape mode settings
- Fixed UIKit scroll view bounce functionality after navigating from SettingsView
- Fixed gesture handling for public profile archive viewing
UI Improvements:
- Added bottom spacing in private, shared, and public workspaces to improve access to …
> VSP-1511 [iOS] Add archive name field to archive profile
